# Generated by Django 3.1.2 on 2020-10-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apply_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_status', models.CharField(choices=[('1', 'Applied'), ('2', 'Viewed'), ('3', 'Processing'), ('4', 'Rejected'), ('5', 'Accepted'), ('6', 'Closed'), ('7', 'None')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_place', models.CharField(max_length=20)),
                ('company_industry', models.CharField(choices=[('1', 'Aerospace Industry'), ('2', 'Agriculture industry'), ('3', 'Banking & Financial Industry'), ('4', 'Computer Hardware Industry'), ('5', 'Education Industry'), ('6', 'Electronics Industry'), ('7', 'Energy Industry'), ('8', 'Entertainment Industry'), ('9', 'Health Care Industry'), ('10', 'Hotel & Tourism Industry'), ('11', 'Manufacturing Industry'), ('12', 'Mining Industry'), ('13', 'Music Industry'), ('14', 'News & Media Industry'), ('15', 'Pharmaceutical Industry'), ('16', 'Software Industry'), ('17', 'Telecommunication industry'), ('18', 'Transport Industry'), ('19', 'Other')], max_length=50)),
                ('company_job_positions', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_place', models.CharField(max_length=20)),
                ('job_type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Internship'), ('4', 'Freelance')], max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('job_category', models.CharField(choices=[('1', 'Aerospace Industry'), ('2', 'Agriculture industry'), ('3', 'Banking & Financial Industry'), ('4', 'Computer Hardware Industry'), ('5', 'Education Industry'), ('6', 'Electronics Industry'), ('7', 'Energy Industry'), ('8', 'Entertainment Industry'), ('9', 'Health Care Industry'), ('10', 'Hotel & Tourism Industry'), ('11', 'Manufacturing Industry'), ('12', 'Mining Industry'), ('13', 'Music Industry'), ('14', 'News & Media Industry'), ('15', 'Pharmaceutical Industry'), ('16', 'Software Industry'), ('17', 'Telecommunication industry'), ('18', 'Transport Industry'), ('19', 'Other')], max_length=50)),
                ('job_skills', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('job_vacancy', models.IntegerField()),
                ('job_experience', models.CharField(max_length=20)),
                ('job_salary', models.CharField(max_length=10)),
                ('job_offer_end', models.DateField()),
                ('job_status', models.CharField(choices=[('1', 'active'), ('2', 'inactive')], max_length=20)),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_place', models.CharField(max_length=20)),
                ('interview_date', models.DateField()),
                ('interview_status', models.CharField(choices=[('1', 'Interview Scheduled'), ('2', 'Accepted'), ('3', 'Declined'), ('4', 'Cancelled'), ('5', 'Selected'), ('6', 'Rejected')], max_length=20)),
                ('created_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
